<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZzzOd.GameLogic</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\od-dotnet\src\OneDragon.Core.Abstractions\OneDragon.Core.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\od-dotnet\src\OneDragon.Core\OneDragon.Core.csproj" />
    <ProjectReference Include="..\..\..\od-dotnet\src\OneDragon.Core.Windows\OneDragon.Core.Windows.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>
