namespace ZzzOd.GameLogic.GameData;

public enum AgentStateCheckWay
{
	COLOR_RANGE_CONNECT = 1,
	BACKGROUND_GRAY_RANGE_LENGTH,
	COLOR_RANGE_EXIST,
	FOREGROUND_COLOR_RANGE_LENGTH,
	FOREGROUND_GRAY_RANGE_LENGTH,
	TEMPLATE_FOUND,
	TEMPLATE_NOT_FOUND,
	COLOR_CHANNEL_MAX_RANGE_EXIST,
	COLOR_CHANNEL_EQUAL_RANGE_CONNECT
}
