namespace ZzzOd.GameLogic.AutoBattle;

public sealed record AutoBattleFlashClassification(int ClassIndex, double ColorConversionElapsedMilliseconds, double PreprocessElapsedMilliseconds, double InferenceElapsedMilliseconds, double PostprocessElapsedMilliseconds, double TotalElapsedMilliseconds);
